[package]
name = "crane"
version = "0.1.0"
authors = ["Sherif Abdou <sherif_abdou@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "crane"
src = "src/lib.rs"

[dependencies]
lazy_static = "1.4.0"